sudo: required
language: generic

services:
  - docker

before_install:
<<<<<<< HEAD
=======
<<<<<<< HEAD
  - docker build -t stephengrider/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true stephengrider/docker-react npm run test
=======
>>>>>>> df519535548988adf023eec548e92b536e8f0083
  - docker build -t jorgelopez21/docker-react -f Dockerfile.dev .

script:

  - docker run -e CI=true jorgelopez21/docker-react npm run test
<<<<<<< HEAD
=======
>>>>>>> 3a6d0874e0be7337d164da87cd5c3769139459cb
>>>>>>> df519535548988adf023eec548e92b536e8f0083

deploy:
  provider: elasticbeanstalk
  region: 'ap-southeast-2'
  app: 'docker4'
  env: 'Docker4-env'
<<<<<<< HEAD
=======
<<<<<<< HEAD
=======
  version: 'Sample Application'
>>>>>>> 3a6d0874e0be7337d164da87cd5c3769139459cb
>>>>>>> df519535548988adf023eec548e92b536e8f0083
  bucket_name: 'elasticbeanstalk-ap-southeast-2-633784099568'
  bucket_path: 'docker'
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY
